---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Register User
      shell: 'cat /var/pgblitz/boxcore.user'
      register: boxuser

    - name: Register Branch
      shell: 'cat /var/pgblitz/boxcore.branch'
      register: boxbranch

    - name: 'Cloning {{boxuser.stdout}} Core Apps'
      git:
        repo: 'https://github.com/{{boxuser.stdout}}/Apps-Core'
        dest: '/opt/coreapps'
        version: '{{boxbranch.stdout}}'
        force: yes
