---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Cloning PGBlitz"
      git:
        repo: "https://github.com/PGBlitz/Install"
        dest: "/opt/pgstage"
        version: "v8.6"
        force: yes
